# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'district_information.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


# district_information_dialog.py
from PyQt5 import QtWidgets, uic
from .exercise_7_10 import CreateCityDistrictProfile
from .district_information import Ui_Information_district

class SecondDialog(QtWidgets.QDialog, Ui_Information_district):
    def __init__(self, district_name):
        super().__init__()
        self.setupUi(self)
        self.district_name_edit.setText(district_name)
        self.textEdit.setText(self.get_district_data(district_name))

    def get_district_data(self, district_name):
        instance = CreateCityDistrictProfile()
        schools, pools = instance.get_district_info(district_name)
        return "Schools: " + str(schools) + "\nPublic Swimming Pools: " + str(pools)    