# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'export_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Export(object):
    def setupUi(self, Export):
        Export.setObjectName("Export")
        Export.resize(400, 300)
        self.pushButton = QtWidgets.QPushButton(Export)
        self.pushButton.setGeometry(QtCore.QRect(130, 230, 141, 31))
        self.pushButton.setObjectName("pushButton")
        self.toolButton = QtWidgets.QToolButton(Export)
        self.toolButton.setGeometry(QtCore.QRect(30, 30, 151, 51))
        self.toolButton.setObjectName("toolButton")
        self.toolButton_2 = QtWidgets.QToolButton(Export)
        self.toolButton_2.setGeometry(QtCore.QRect(30, 120, 151, 51))
        self.toolButton_2.setObjectName("toolButton_2")
        self.lineEdit_pdf_outputpath = QtWidgets.QLineEdit(Export)
        self.lineEdit_pdf_outputpath.setGeometry(QtCore.QRect(30, 90, 151, 16))
        self.lineEdit_pdf_outputpath.setObjectName("lineEdit_pdf_outputpath")
        self.lineEdit_csv_outputpath = QtWidgets.QLineEdit(Export)
        self.lineEdit_csv_outputpath.setGeometry(QtCore.QRect(30, 180, 151, 16))
        self.lineEdit_csv_outputpath.setObjectName("lineEdit_csv_outputpath")
        self.pushButton_pfd = QtWidgets.QPushButton(Export)
        self.pushButton_pfd.setGeometry(QtCore.QRect(180, 90, 31, 21))
        self.pushButton_pfd.setText("")
        self.pushButton_pfd.setObjectName("pushButton_pfd")
        self.pushButton_csv = QtWidgets.QPushButton(Export)
        self.pushButton_csv.setGeometry(QtCore.QRect(180, 180, 31, 21))
        self.pushButton_csv.setText("")
        self.pushButton_csv.setObjectName("pushButton_csv")
        self.textBrowser_export = QtWidgets.QTextBrowser(Export)
        self.textBrowser_export.setGeometry(QtCore.QRect(220, 20, 161, 181))
        self.textBrowser_export.setObjectName("textBrowser_export")

        self.retranslateUi(Export)
        QtCore.QMetaObject.connectSlotsByName(Export)

    def retranslateUi(self, Export):
        _translate = QtCore.QCoreApplication.translate
        Export.setWindowTitle(_translate("Export", "Dialog"))
        self.pushButton.setText(_translate("Export", "OK"))
        self.toolButton.setText(_translate("Export", "Export as *.pdf "))
        self.toolButton_2.setText(_translate("Export", "Export as *.csv"))
        self.textBrowser_export.setHtml(_translate("Export", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"li.unchecked::marker { content: \"\\2610\"; }\n"
"li.checked::marker { content: \"\\2612\"; }\n"
"</style></head><body style=\" font-family:\'.AppleSystemUIFont\'; font-size:13pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">District profile with some information. You can choose between a csv or pdf file to download the information. Included information on the topics schools, public swimming pools etc. </p></body></html>"))
