# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'district_information.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Information_district(object):
    def setupUi(self, Information_district):
        Information_district.setObjectName("Information_district")
        Information_district.resize(400, 300)
        self.buttonBox = QtWidgets.QDialogButtonBox(Information_district)
        self.buttonBox.setGeometry(QtCore.QRect(30, 240, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel | QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        
        self.label = QtWidgets.QLabel(Information_district)
        self.label.setGeometry(QtCore.QRect(20, 10, 271, 41))
        self.label.setObjectName("label")
        
        self.textEdit = QtWidgets.QTextEdit(Information_district)
        self.textEdit.setGeometry(QtCore.QRect(20, 80, 211, 51))
        self.textEdit.setObjectName("textEdit")
        
        self.district_name_edit = QtWidgets.QTextEdit(Information_district)
        self.district_name_edit.setGeometry(QtCore.QRect(20, 40, 91, 31))
        self.district_name_edit.setObjectName("district_name_edit")

        self.retranslateUi(Information_district)
        self.buttonBox.accepted.connect(Information_district.accept) # type: ignore
        self.buttonBox.rejected.connect(Information_district.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Information_district)

    def retranslateUi(self, Information_district):
        _translate = QtCore.QCoreApplication.translate
        Information_district.setWindowTitle(_translate("Information_district", "Dialog"))
        self.label.setText(_translate("Information_district", "District schools and public swimming pools"))





